### PR TITLE
Laravel 11 compatibility.

### PR DESCRIPTION
**Pull request by HamzaAlayed**
Update symfony/process to version 7 & 6 for Laravel 9&11 compatibility

### CODE REVIEW

**Comment by rhnkyr** [comment]
@antonioribeiro @HamzaAlayed any news on this PR?

**Comment by secrethash** [comment]
@antonioribeiro any update for this PR?

**Comment by antonioribeiro** [comment]
Hello @HamzaAlayed , why you are adding `"roave/security-advisories": "dev-latest"`?

**Comment by xnekv03** [comment]
@antonioribeiro it would be great if you can merge this PR soon, thank you

**Comment by antonioribeiro** [comment]
Guys, it’s not mergeable the way it is, still waiting for @HamzaAlayed to answer my last question, sorry

**Comment by HamzaAlayed** [comment]
@antonioribeiro, I'm using `"roave/security-advisories": "dev-latest"` to make sure there is no security issues any any packages used in the `composer`, Anyway it's optional and it can remove if it doesn't help in development.

**Comment by antonioribeiro** [comment]
Yes, please remove, we can think about adding it later if needed

**Comment by HamzaAlayed** [comment]
@antonioribeiro Removed!

**Comment by xnekv03** [comment]
thank you

**Comment by antonioribeiro** [comment]
Tests are failing hard: https://github.com/antonioribeiro/version/actions/runs/10496601040/job/29077623981

I cannot tag a new version from here, I’m on vacation and computerless ☺️

**Comment by xnekv03** [comment]
Any time estimate when this might be done? Thanks

**Pull request merged**
