### PR TITLE
Laravel 6.0 support

### PR DESCRIPTION
**Pull request by AraneaDev**

### CODE REVIEW

**Comment by checkerschaf** [comment]
Would really appreciate if this gets merged soon :)

**Comment by antonioribeiro** [comment]
Sorry, but this is wrong in so many ways...

**Comment by antonioribeiro** [comment]
I will update it to Laravel 6 soon. Unfortunately I have too many Laravel packages to update, this is only one of them.

**Comment by antonioribeiro** [comment]
Should be fixed now.

**Pull request closed without merging**
