### PR TITLE
Added date and time to version control

### PR DESCRIPTION
**Pull request by luanrodrigues**
Added date and time to version control

### CODE REVIEW

**Comment by antonioribeiro** [comment]
I like the idea, but date is kind of a complex thing to format in different locales. At first I don't like the idea of it being formatted by default in m/d/y, y/m/d h:m, would be my first choice, but, still, we would have to give people the chance to choose their preferred format themselves, and, maybe break it like it's done for the version:

```
date: "{$year}-{$month}-{$day} {$hour}:{$minute}"
```

**Comment by luanrodrigues** [comment]
how about the parameters at file 'src/config/version.yml' it would be 5 more parameters instead of one, the way you suggested  it's a bit less flexible

**Comment by luanrodrigues** [comment]
the date format could be chosen using parameter **_dateFormat: 'm-d-Y H:i'_** see https://github.com/antonioribeiro/version/pull/58/files#diff-da62bfdb82dba6b474efb5d586080abbR9

**Comment by antonioribeiro** [comment]
Yeah, I get that but the .yml contains more formats, to be used in some other features of the package:

```
format:
  major: "{$major}"
  minor: "{$minor}"
  patch: "{$patch}"
  build: "{$build}"
  version: "{$major}.{$minor}.{$patch} (build {$build})"
  full: "version {{'format.version'}}"
  compact: "v{$major}.{$minor}.{$patch}-{$build}"
  ## add as many formats as you need !!!!
```

**Pull request closed without merging**
