### PR TITLE
Update to support Laravel 7.x

### PR DESCRIPTION
**Pull request by softquantum**
Didn't check if $process = Process::fromShellCommandline() is also part of the older versions of symfony/process (<5.0)

### CODE REVIEW

**Comment by herroworrd** [comment]
Can we get this pushed through?

**Comment by timramseyjr** [comment]
@antonioribeiro I was curious if you had an ETA when this might be merged?

**Comment by softquantum** [comment]
In the meantime Antonio has the time to work on it, you can just fork the the repo, apply the changes  and add it to your composer like this.  Works like a charm.

```
"repositories":[
        {
            "type": "vcs",
            "url": "https://github.com/**yourforkedrepo**/version"
        }
    ],
```

**Comment by antonioribeiro** [comment]
@softquantum, You should add `.idea` to your global .gitignore, not everyone uses PHPStorm, but, yeah, I do :)

But thanks for this PR and sorry for not merging it before.

**Pull request merged**
